// <auto-generated />
namespace E_commerce_ASP.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class productinternationalization : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(productinternationalization));
        
        string IMigrationMetadata.Id
        {
            get { return "202201221223177_product internationalization"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
