// <auto-generated />
namespace E_commerce_ASP.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class adding_other_tables : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(adding_other_tables));
        
        string IMigrationMetadata.Id
        {
            get { return "202201072201129_adding_other_tables"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
