// <auto-generated />
namespace E_commerce_ASP.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class remove_lists_fields_from_product_model : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(remove_lists_fields_from_product_model));
        
        string IMigrationMetadata.Id
        {
            get { return "202201302346554_remove_lists_fields_from_product_model"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
