//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_commerce_ASP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        public string Id { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<bool> IsInFavList { get; set; }
        public Nullable<bool> IsInBlackList { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public string UserId { get; set; }
        public string Image { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual Categories Categories { get; set; }
    }
}
